# Generated by Django 3.0.3 on 2020-08-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='max_price_range',
        ),
        migrations.RemoveField(
            model_name='business',
            name='min_price_range',
        ),
    ]
