# Generated by Django 3.0.3 on 2020-08-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20200823_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('business', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.Business')),
            ],
        ),
    ]
