# Generated by Django 3.0.3 on 2020-08-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_auto_20200826_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
