# Generated by Django 3.0.3 on 2020-08-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_auto_20200827_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
